# Generated by Django 5.0.4 on 2024-05-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13)),
                ('category', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('availability_status', models.BooleanField(default=True)),
                ('borrower', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
